### ISSUE TITLE
TypeError: str.split is not a function

### ISSUE THREAD

**Issue by calgara12** [lubien/popura#20]
I get this error and i don't know how to fix it.

TypeError: str.split is not a function
    at splitBy (C:\Users\privat\Documents\GIT\MangaRD\node_modules\popura\lib\utils\index.js:103:20)
    at convertFieldTypes (C:\Users\privat\Documents\GIT\MangaRD\node_modules\popura\lib\utils\convert-field-types.js:55:35)
    at cleanApiData (C:\Users\privat\Documents\GIT\MangaRD\node_modules\popura\lib\utils\clean-api-data.js:33:39)
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by lubien** [comment]
Could you provide the code that errors or an example like it?

**Comment by calgara12** [comment]
Of course. For explanation im trying to establish a Manga Database currently im trying to get all mangas from kissmanga. With your module i want to add additional information for the manga that hakuneko does not provide like score, image, description...
Im just starting to learn javascript and node js, if you need more just let me know.  Thanks for your tool, and for your fast response.
![capture](https://user-images.githubusercontent.com/28657023/26966873-34ddb772-4cfc-11e7-8594-6135ebc13e28.PNG)

**Comment by lubien** [comment]
Sorry for delaying my answer all this time, I'm working on a tight schedule here.

My library do lots of checks and transformations before I can give you an usable data from MAL. 

When I read `str.split is not a function` most like there where a case I was expecting.

Sadly I wont find any time to look carefully onto this soon but your print will be useful.

One thing that could be helpful too is if you know exactly what entry had this error like "when I search for a manga with title 'something'".
